name: deploy on push
on:
  push:
    branches:
      - main
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - name: check out the code to build server
      uses: actions/checkout@v2
    - name: copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PROJECT_MOVIE_HOST }}
        username: ${{ secrets.PROJECT_MOVIE_SSH_USER_NAME }}
        port: ${{ secrets.PROJECT_MOVIE_PORT }}
        key: ${{ secrets.PROJECT_MOVIE_KEY }}
        source: "./*"
        target: "/var/www/html/"